apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - namespace.yaml
secretGenerator:
  - name: pihole-secret
    envs:
      - secret.pihole.env
  - name: cloudflare-secret
    envs:
      - secret.cloudflare.env
generatorOptions:
  disableNameSuffixHash: true
