apiVersion: v1
kind: ConfigMap
metadata:
  name: reddit-meaningofwords-config
data:
  REDDIT_PROMPT_PATH: /reddit/prompt.txt
  REDDIT_SIGNATURE_PATH: /reddit/signature.md
  REDDIT_DICTIONARY_PATH: /reddit/dictionary.json
  REDDIT_SUBREDDITS: "polska+bydgoszcz+bytom+gdansk+krakow+lodz+poznan+szczecin+trojmiasto+warsaw+wroclaw+learnpolish+polskanaluzie+polskapolityka+polska_wpz"
  LOG_LEVEL: INFO

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: reddit-meaningofwords-files
data:
  dictionary.json: |
    {
      "co najmniej": {
        "explanations": [
          "Zgodnie z zasadami ortografii jzyka polskiego 'co najmniej' powinnimy zapisywa osobno, oddzielajc partyku wzmacniajc 'co' od przys贸wka 'najmniej'. Nakazuje to regua m贸wica, 偶e poszczeg贸lne czony wyra偶enia zaimkowego, czyli poczenia zaimka i nastpujcej po nim innej czci mowy, piszemy rozdzielnie."
        ],
        "search_rule": "\\bconajmniej\\b"
      },
      "dlatego 偶e": {
        "explanations": [
          "Poprawnym zapisem jest forma 'dlatego 偶e', poniewa偶 jest to sp贸jnik skadajcy si z dw贸ch nierozcznych sp贸jnik贸w, kt贸re razem tworz cao znaczeniow. 'Dlatego bo' jest niepoprawne ze wzgldu na podkrelenie relacji przyczynowej, kt贸re wyra偶a zar贸wno 'dlatego', jak i 'bo', a wic s synonimami, za cae wyra偶enie 'dlatego bo' jest pleonazmem (czyli na przykad jak 'maso malane'). Przecinek umieszczamy najczciej przed caym sp贸jnikiem zo偶onym 'dlatego 偶e'."
        ],
        "search_rule": "\\bdlatego[,]{0,1} bo\\b"
      },
      "dzie dzisiejszy": {
        "explanations": [
          "Poczenie 'w dniu dzisiejszym' jest nacechowane oficjalnoci i pojawi si mo偶e jedynie w tekstach oficjalnych i urzdowych, cho nie mo偶na zapomnie, 偶e sowniki poprawnej polszczyzny przestrzegaj przed konstrukcj 'dzie dzisiejszy', kt贸ra jest nadu偶ywana wanie w wypowiedziach utrzymanych w stylu oficjalnym i urzdowym. Przys贸wki dzisiaj i dzi s wyrazami o znaczeniu neutralnym, s zatem poprawne w ka偶dym tekcie."
        ],
        "search_rule": "\\b(dniu|dzien) (dzisiejszy|jutrzejszy|wczorajszy)[m]{0,1}\\b"
      },
      "in vitro": {
        "explanations": [
          "'In vitro' wywodzi si z jzyka aciskiego, gdzie dosownie tumaczone jest jako 'w szkle'. Skada si z przyimka 'in' oraz rzeczownika 'vitro', std polszczyzna przeja zapis rozczny."
        ],
        "search_rule": "\\bin[vw]itro\\b"
      },
      "na co dzie": {
        "explanations": [
          "Zapis rozczny 'na co dzie' okrela zasada konwencjonalna. Oznacza to, 偶e przyjtej pisowni nie rozstrzyga ani wymowa, ani pochodzenie historyczne. Warto jednak zwr贸ci uwag na budow tego wyra偶enia: 'na' jest przyimkiem, kt贸ry bardzo czsto wchodzi w skad wyra偶e przyimkowych, jakie zawsze zapisujemy rozcznie. Natomiast 'co dzie' nale偶y do wyra偶e zaimkowych r贸wnie偶 pisanych rozcznie. Zatem ka偶dy element tej frazy musi zosta zapisany oddzielnie. Bdne 'nacodzie' wynika najpewniej z analogii do 'codziennie', jednak rozkad czci mowy wskazuje, 偶e s to trzy osobne wyrazy."
        ],
        "search_rule": "\\bna[ ]{0,1}codzien\\b"
      },
      "na pewno": {
        "explanations": [
          "Wyra偶enie 'na pewno' wywodzi si od prasowiaskiej formy przymiotnika rodzaju nijakiego 'pewno'. Zar贸wno w przypadku tego sformuowania, jak i podobnych: na lewo, na prawo, na okrgo, na nowo, obowizuje pisownia rozdzielna."
        ],
        "search_rule": "\\bnapewno\\b"
      },
      "na prawd": {
        "explanations": [
          "'Naprawd' pisane cznie to partykua, za pomoc kt贸rej mo偶emy kogo przekona, 偶e mamy racj, i potwierdzi prawdziwo tego, co m贸wimy, np. 'Naprawd byam wczoraj w domu i nigdzie nie wychodziam'",
          "Przy u偶yciu 'naprawd' mo偶emy tak偶e wyrazi niedowierzanie lub zdziwienie, np. 'Nie wierz, 偶e naprawd to powiedziaa.'",
          "Zapis 'na prawd' zastosujemy wycznie w przypadkach, gdy mowa o rzeczowniku 'prawda' w bierniku liczby pojedynczej ('prawd') zestawionym z przyimkiem 'na'."
        ],
        "search_rule": "\\bna prawde\\b"
      },
      "na razie": {
        "explanations": [
          "Wyra偶enie przyimkowe 'na razie', penice funkcje przys贸wka, u偶ywamy w znaczeniu: tymczasem, teraz, jeszcze. Jest to r贸wnie偶 potoczna formua po偶egnalna. W obu powy偶szych znaczeniach poprawny jest rozdzielny zapis."
        ],
        "search_rule": "\\bnarazie\\b"
      },
      "naprzeciwko": {
        "explanations": [
          "Niegdy 'naprzeciwko' byo poczeniem przyimkowym. We wsp贸czesnej polszczy藕nie funkcjonuje jako zrost wyraz贸w 'na' i 'przeciw'. Takie konstrukcje zawsze zapisywane s cznie."
        ],
        "search_rule": "\\bna przeciwko\\b"
      },
      "nie wiem": {
        "explanations": [
          "Zgodnie z obowizujcymi w jzyku polskim zasadami ortograficznymi partyku nie bdc wykadnikiem zaprzeczenia piszemy rozdzielnie przed czasownikami."
        ],
        "search_rule": "\\bniewiem\\b"
      },
      "poza tym": {
        "explanations": [
          "Zwrot 'poza tym' jest tak zwanym wyra偶eniem przyimkowym. W jzyku polskim wikszo tych wyra偶e zapisujemy rozdzielnie."
        ],
        "search_rule": "\\b(po za tym|pozatym)\\b"
      },
      "sprzed": {
        "explanations": [
          "Przyimek 'spod' i przyimek 'sprzed' zawsze piszemy cznie i przez 's-'. Nie ma takiego kontekstu, w kt贸rych mogo by zosta uznane za poprawne napisanie 'z pod' lub 'z przed'. Od 1936 roku, czyli od czasu reformy ortografii, przyimki 'spod' i 'sprzed' s zrostami i nale偶y je zapisywa cznie."
        ],
        "search_rule": "\\bz[ ]{0,1}(przed|pod)\\b"
      },
      "szedem": {
        "explanations": [
          "Formy 'szedem', 'poszedem', 'doszedem' s zgodne z systemem gramatycznym polszczyzny, a formy 'szem', 'poszem', 'doszem' s niepoprawne. Skoro m贸wimy: 'on szed', na nie: on 'sz', to poprawnie m贸wimy i piszemy r贸wnie偶: 'ja szedem'."
        ],
        "search_rule": "\\b(do|wy|p(o|rzy)){0,1}szlem\\b"
      },
      "w og贸le": {
        "explanations": [
          "Wyra偶enie przyimkowe 'w og贸le' piszemy rozdzielnie. Podobnie jak 'na og贸' i 'z og贸em'. Wszystkie bowiem pochodz od rzeczownika 'og贸'."
        ],
        "search_rule": "\\bwog[ou]le\\b"
      },
      "wzi": {
        "explanations": [
          "Jedyn dozwolon jest 'wzi'. W wielu przypadkach 'wzi' tworzone jest przez podobiestwo do innych czasownik贸w zakoczonych na '-', takich jak: 'p贸j' czy 'usi'. Aby uatwi zapamitanie tej formy, polecam skojarzenie z czasownikiem 'bra': 'wzi', a nie 'wzi', bo nie mo偶na czego 'bra'."
        ],
        "search_rule": "\\bwzia[sz]c\\b"
      },
      "z powrotem": {
        "explanations": [
          "Zgodnie z zasadami jzyka polskiego wyra偶enie 'z powrotem' powinnimy zapisa rozdzielnie z przyimkiem 'z'. Nietrudno w tym przypadku o pomyk. Cz wyra偶e pisanych etymologicznie osobno (regua obowizywaa do 1938 roku) zgodnie z obowizujcymi zasadami zapisuje si czenie w takiej postaci: 'sponad' dawniej: 'z ponad' 'sprzed' dawniej: 'z przed'. Jednak wyra偶enie 'z powrotem' nie zmienio swojej formy."
        ],
        "search_rule": "\\b[sz]powrotem\\b"
      },
      "z rzdu": {
        "explanations": [
          "Wyra偶enie przyimkowe 'pod rzd' traktowane jest jako kalka rosyjskiego '锌芯写写', a zatem polega na dokadnym odwzorowaniu obcej konstrukcji i przeniesieniu jej na rodzimy grunt. Mamy tu wic do czynienia z nieakceptowanym przez normatywist贸w zapo偶yczeniem strukturalnym. Wzorcowe odpowiedniki tego sformuowania to: 'z rzdu', 'po kolei', 'kolejno', 'jeden po drugim'."
        ],
        "search_rule": "\\bpod rzad\\b"
      },
      "zodziei": {
        "explanations": [
          "Prawidowa pisownia tego rzeczownika to 'zodziei'. Bdny zapis wynika z analogii do reguy ortograficznej m贸wicej, 偶e po samogoskach pisane jest 'j', oraz wymowy, gdzie 'j' jest wyra藕nie syszane ze wzgldu na uproszczenia w artykulacji."
        ],
        "search_rule": "\\bzlodzieji\\b"
      }
    }
  prompt.txt: |
    Wciel si w rol jzykoznawcy jzyka polskiego.
    Podam ci wyra偶enie w poprawnej lub bdnej formie.
    Nastpnie podam ci zasady pisowni dotyczce tego lub podobnych wyra偶e.
    Sprawd藕 czy podanym przeze mnie tekcie zostanie u偶yta poprawna forma wyra偶enia.
    Wyjanij jakie zasady poprawnej pisowni dotyczn tego wyra偶enia, opierajc si o zasady, kt贸re ci podam.
    Na koniec podaj poprawn wersj zdania.
  signature.md: |
     Bip bop, jestem bot. 

    Szukam najczciej popenianych bd贸w w internecie:
    [2022](https://nadwyraz.com/blog-raport-100-najczesciej-popelnianych-bledow-w-internecie-w-2022),
    [2023](https://nadwyraz.com/blog-raport-50-najczesciej-popelnianych-bledow-w-internecie-w-2023)
