apiVersion: v1
kind: ConfigMap
metadata:
  name: reddit-meaningofwords-config
data:
  REDDIT_PROMPT_PATH: /reddit/prompt.txt
  REDDIT_SIGNATURE_PATH: /reddit/signature.md
  REDDIT_DICTIONARY_PATH: /reddit/dictionary.json
  REDDIT_SUBREDDITS: "polska+bydgoszcz+bytom+gdansk+krakow+lodz+poznan+szczecin+trojmiasto+warsaw+wroclaw+learnpolish+polskanaluzie+polskapolityka+polska_wpz"
  LOG_LEVEL: INFO

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: reddit-meaningofwords-files
data:
  dictionary.json: |
    {
      "co najmniej": {
        "explanations": [
          "Zgodnie z zasadami ortografii jÄ™zyka polskiego 'co najmniej' powinniÅ›my zapisywaÄ‡ osobno, oddzielajÄ…c partykuÅ‚Ä™ wzmacniajÄ…cÄ… 'co' od przysÅ‚Ã³wka 'najmniej'. Nakazuje to reguÅ‚a mÃ³wiÄ…ca, Å¼e poszczegÃ³lne czÅ‚ony wyraÅ¼enia zaimkowego, czyli poÅ‚Ä…czenia zaimka i nastÄ™pujÄ…cej po nim innej czÄ™Å›ci mowy, piszemy rozdzielnie."
        ],
        "search_rule": "\\bconajmniej\\b"
      },
      "dlatego Å¼e": {
        "explanations": [
          "Poprawnym zapisem jest forma 'dlatego Å¼e', poniewaÅ¼ jest to spÃ³jnik skÅ‚adajÄ…cy siÄ™ z dwÃ³ch nierozÅ‚Ä…cznych spÃ³jnikÃ³w, ktÃ³re razem tworzÄ… caÅ‚oÅ›Ä‡ znaczeniowÄ…. 'Dlatego bo' jest niepoprawne ze wzglÄ™du na podkreÅ›lenie relacji przyczynowej, ktÃ³re wyraÅ¼a zarÃ³wno 'dlatego', jak i 'bo', a wiÄ™c sÄ… synonimami, zaÅ› caÅ‚e wyraÅ¼enie 'dlatego bo' jest pleonazmem (czyli na przykÅ‚ad jak 'masÅ‚o maÅ›lane'). Przecinek umieszczamy najczÄ™Å›ciej przed caÅ‚ym spÃ³jnikiem zÅ‚oÅ¼onym 'dlatego Å¼e'."
        ],
        "search_rule": "\\bdlatego[,]{0,1} bo\\b"
      },
      "dzieÅ„ dzisiejszy": {
        "explanations": [
          "PoÅ‚Ä…czenie 'w dniu dzisiejszym' jest nacechowane oficjalnoÅ›ciÄ… i pojawiÄ‡ siÄ™ moÅ¼e jedynie w tekstach oficjalnych i urzÄ™dowych, choÄ‡ nie moÅ¼na zapomnieÄ‡, Å¼e sÅ‚owniki poprawnej polszczyzny przestrzegajÄ… przed konstrukcjÄ… 'dzieÅ„ dzisiejszy', ktÃ³ra jest naduÅ¼ywana wÅ‚aÅ›nie w wypowiedziach utrzymanych w stylu oficjalnym i urzÄ™dowym. PrzysÅ‚Ã³wki dzisiaj i dziÅ› sÄ… wyrazami o znaczeniu neutralnym, sÄ… zatem poprawne w kaÅ¼dym tekÅ›cie."
        ],
        "search_rule": "\\b(dniu|dzien) (dzisiejszy|jutrzejszy|wczorajszy)[m]{0,1}\\b"
      },
      "in vitro": {
        "explanations": [
          "'In vitro' wywodzi siÄ™ z jÄ™zyka Å‚aciÅ„skiego, gdzie dosÅ‚ownie tÅ‚umaczone jest jako 'w szkle'. SkÅ‚ada siÄ™ z przyimka 'in' oraz rzeczownika 'vitro', stÄ…d polszczyzna przejÄ™Å‚a zapis rozÅ‚Ä…czny."
        ],
        "search_rule": "\\bin[vw]itro\\b"
      },
      "na co dzieÅ„": {
        "explanations": [
          "Zapis rozÅ‚Ä…czny 'na co dzieÅ„' okreÅ›la zasada konwencjonalna. Oznacza to, Å¼e przyjÄ™tej pisowni nie rozstrzyga ani wymowa, ani pochodzenie historyczne. Warto jednak zwrÃ³ciÄ‡ uwagÄ™ na budowÄ™ tego wyraÅ¼enia: 'na' jest przyimkiem, ktÃ³ry bardzo czÄ™sto wchodzi w skÅ‚ad wyraÅ¼eÅ„ przyimkowych, jakie zawsze zapisujemy rozÅ‚Ä…cznie. Natomiast 'co dzieÅ„' naleÅ¼y do wyraÅ¼eÅ„ zaimkowych rÃ³wnieÅ¼ pisanych rozÅ‚Ä…cznie. Zatem kaÅ¼dy element tej frazy musi zostaÄ‡ zapisany oddzielnie. BÅ‚Ä™dne 'nacodzieÅ„' wynika najpewniej z analogii do 'codziennie', jednak rozkÅ‚ad czÄ™Å›ci mowy wskazuje, Å¼e sÄ… to trzy osobne wyrazy."
        ],
        "search_rule": "\\bna[ ]{0,1}codzien\\b"
      },
      "na pewno": {
        "explanations": [
          "WyraÅ¼enie 'na pewno' wywodzi siÄ™ od prasÅ‚owiaÅ„skiej formy przymiotnika rodzaju nijakiego 'pewno'. ZarÃ³wno w przypadku tego sformuÅ‚owania, jak i podobnych: na lewo, na prawo, na okrÄ…gÅ‚o, na nowo, obowiÄ…zuje pisownia rozdzielna."
        ],
        "search_rule": "\\bnapewno\\b"
      },
      "na prawdÄ™": {
        "explanations": [
          "'NaprawdÄ™' pisane Å‚Ä…cznie to partykuÅ‚a, za pomocÄ… ktÃ³rej moÅ¼emy kogoÅ› przekonaÄ‡, Å¼e mamy racjÄ™, i potwierdziÄ‡ prawdziwoÅ›Ä‡ tego, co mÃ³wimy, np. 'NaprawdÄ™ byÅ‚am wczoraj w domu i nigdzie nie wychodziÅ‚am'",
          "Przy uÅ¼yciu 'naprawdÄ™' moÅ¼emy takÅ¼e wyraziÄ‡ niedowierzanie lub zdziwienie, np. 'Nie wierzÄ™, Å¼e naprawdÄ™ to powiedziaÅ‚aÅ›.'",
          "Zapis 'na prawdÄ™' zastosujemy wyÅ‚Ä…cznie w przypadkach, gdy mowa o rzeczowniku 'prawda' w bierniku liczby pojedynczej ('prawdÄ™') zestawionym z przyimkiem 'na'."
        ],
        "search_rule": "\\bna prawde\\b"
      },
      "na razie": {
        "explanations": [
          "WyraÅ¼enie przyimkowe 'na razie', peÅ‚niÄ…ce funkcje przysÅ‚Ã³wka, uÅ¼ywamy w znaczeniu: tymczasem, teraz, jeszcze. Jest to rÃ³wnieÅ¼ potoczna formuÅ‚a poÅ¼egnalna. W obu powyÅ¼szych znaczeniach poprawny jest rozdzielny zapis."
        ],
        "search_rule": "\\bnarazie\\b"
      },
      "naprzeciwko": {
        "explanations": [
          "NiegdyÅ› 'naprzeciwko' byÅ‚o poÅ‚Ä…czeniem przyimkowym. We wspÃ³Å‚czesnej polszczyÅºnie funkcjonuje jako zrost wyrazÃ³w 'na' i 'przeciw'. Takie konstrukcje zawsze zapisywane sÄ… Å‚Ä…cznie."
        ],
        "search_rule": "\\bna przeciwko\\b"
      },
      "nie wiem": {
        "explanations": [
          "Zgodnie z obowiÄ…zujÄ…cymi w jÄ™zyku polskim zasadami ortograficznymi partykuÅ‚Ä™ nie bÄ™dÄ…cÄ… wykÅ‚adnikiem zaprzeczenia piszemy rozdzielnie przed czasownikami."
        ],
        "search_rule": "\\bniewiem\\b"
      },
      "poza tym": {
        "explanations": [
          "WyraÅ¼enie przyimkowe 'poza tym' - bÄ™dÄ…ce partykuÅ‚Ä… wprowadzajÄ…cÄ… nowe informacje do wypowiedzi â€“ zapisujemy, rozdzielajÄ…c przyimek 'poza' od zaimka wskazujÄ…cego 'tym'. Niedopuszczalna jest zarÃ³wno pisownia rozdzielna przybierajÄ…ca formÄ™: 'po za tym', jak rÃ³wnieÅ¼ pisownia Å‚Ä…czna: 'pozatym' (wzorujÄ…ca siÄ™ zapisie wyrazu 'ponadto')."
        ],
        "search_rule": "\\b(po za tym|pozatym)\\b"
      },
      "sprzed": {
        "explanations": [
          "Przyimek 'spod' i przyimek 'sprzed' zawsze piszemy Å‚Ä…cznie i przez 's-'. Nie ma takiego kontekstu, w ktÃ³rych mogÅ‚o by zostaÄ‡ uznane za poprawne napisanie 'z pod' lub 'z przed'. Od 1936 roku, czyli od czasu reformy ortografii, przyimki 'spod' i 'sprzed' sÄ… zrostami i naleÅ¼y je zapisywaÄ‡ Å‚Ä…cznie."
        ],
        "search_rule": "\\bz[ ]{0,1}(przed|pod)\\b"
      },
      "szedÅ‚em": {
        "explanations": [
          "Formy 'szedÅ‚em', 'poszedÅ‚em', 'doszedÅ‚em' sÄ… zgodne z systemem gramatycznym polszczyzny, a formy 'szÅ‚em', 'poszÅ‚em', 'doszÅ‚em' sÄ… niepoprawne. Skoro mÃ³wimy: 'on szedÅ‚', na nie: on 'szÅ‚', to poprawnie mÃ³wimy i piszemy rÃ³wnieÅ¼: 'ja szedÅ‚em'."
        ],
        "search_rule": "\\b(do|wy|p(o|rzy)){0,1}szlem\\b"
      },
      "w ogÃ³le": {
        "explanations": [
          "WyraÅ¼enie przyimkowe 'w ogÃ³le' piszemy rozdzielnie. Podobnie jak 'na ogÃ³Å‚' i 'z ogÃ³Å‚em'. Wszystkie bowiem pochodzÄ… od rzeczownika 'ogÃ³Å‚'."
        ],
        "search_rule": "\\bwog[ou]le\\b"
      },
      "wziÄ…Ä‡": {
        "explanations": [
          "JedynÄ… dozwolonÄ… jest 'wziÄ…Ä‡'. W wielu przypadkach 'wziÄ…Å›Ä‡' tworzone jest przez podobieÅ„stwo do innych czasownikÃ³w zakoÅ„czonych na '-Å›Ä‡', takich jak: 'pÃ³jÅ›Ä‡' czy 'usiÄ…Å›Ä‡'. Aby uÅ‚atwiÄ‡ zapamiÄ™tanie tej formy, polecam skojarzenie z czasownikiem 'braÄ‡': 'wziÄ…Ä‡', a nie 'wziÄ…Å›Ä‡', bo nie moÅ¼na czegoÅ› 'braÅ›Ä‡'."
        ],
        "search_rule": "\\bwzia[sz]c\\b"
      },
      "z powrotem": {
        "explanations": [
          "Zgodnie z zasadami jÄ™zyka polskiego wyraÅ¼enie 'z powrotem' powinniÅ›my zapisaÄ‡ rozdzielnie z przyimkiem 'z'. Nietrudno w tym przypadku o pomyÅ‚kÄ™. CzÄ™Å›Ä‡ wyraÅ¼eÅ„ pisanych etymologicznie osobno (reguÅ‚a obowiÄ…zywaÅ‚a do 1938 roku) zgodnie z obowiÄ…zujÄ…cymi zasadami zapisuje siÄ™ Å‚Ä…czenie w takiej postaci: 'sponad' dawniej: 'z ponad' 'sprzed' dawniej: 'z przed'. Jednak wyraÅ¼enie 'z powrotem' nie zmieniÅ‚o swojej formy."
        ],
        "search_rule": "\\b[sz]powrotem\\b"
      },
      "zÅ‚odziei": {
        "explanations": [
          "PrawidÅ‚owa pisownia tego rzeczownika to 'zÅ‚odziei'. BÅ‚Ä™dny zapis wynika z analogii do reguÅ‚y ortograficznej mÃ³wiÄ…cej, Å¼e po samogÅ‚oskach pisane jest 'j', oraz wymowy, gdzie 'j' jest wyraÅºnie sÅ‚yszane ze wzglÄ™du na uproszczenia w artykulacji."
        ],
        "search_rule": "\\bzlodzieji\\b"
      }
    }
  prompt.txt: |
    Wciel siÄ™ w rolÄ™ jÄ™zykoznawcy jÄ™zyka polskiego.
    Podam ci wyraÅ¼enie w poprawnej lub bÅ‚Ä™dnej formie.
    NastpÄ™nie podam ci zasady pisowni dotyczÄ…ce tego lub podobnych wyraÅ¼eÅ„.
    SprawdÅº czy podanym przeze mnie tekÅ›cie zostanie uÅ¼yta poprawna forma wyraÅ¼enia.
    WyjaÅ›nij jakie zasady poprawnej pisowni dotycznÄ… tego wyraÅ¼enia, opierajÄ…c siÄ™ o zasady, ktÃ³re ci podam.
    Na koniec podaj poprawnÄ… wersjÄ™ zdania.
  signature.md: |
    ğŸ¤– Bip bop, jestem bot. ğŸ¤–

    Szukam najczÄ™Å›ciej popeÅ‚nianych bÅ‚Ä™dÃ³w w internecie:
    [2022](https://nadwyraz.com/blog-raport-100-najczesciej-popelnianych-bledow-w-internecie-w-2022),
    [2023](https://nadwyraz.com/blog-raport-50-najczesciej-popelnianych-bledow-w-internecie-w-2023)
