tunnel: e48d5ef2-41f9-4ca5-a8bf-f60af8d77921
credentials-file: /etc/cloudflared/credentials/e48d5ef2-41f9-4ca5-a8bf-f60af8d77921.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
  - service: https://traefik.traefik.svc.cluster.local:443
