kind: Gateway
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: https
  namespace: kgateway-system
  labels:
    dns-type: internal
  annotations:
    cert-manager.io/cluster-issuer: "lets-encrypt-prod"
spec:
  gatewayClassName: kgateway
  listeners:
    - name: http
      protocol: HTTP
      port: 80
  allowedListeners:
    namespaces:
      from: All
