apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  destination:
    namespace: kgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kgateway-crds
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    targetRevision: v2.1.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kgateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  destination:
    namespace: kgateway-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kgateway
    repoURL: cr.kgateway.dev/kgateway-dev/charts
    targetRevision: v2.1.*
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
