apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tandoor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: cluster
      repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.3.1
      helm:
        releaseName: database
        valueFiles:
          - $repo/manifests/base/tandoor/database-values.yaml
    - repoURL: 'https://github.com/theadzik/homelab'
      path: manifests/base/tandoor
      targetRevision: main
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: tandoor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
