apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crds
  annotations:
    argocd.argoproj.io/sync-wave: "-11"
spec:
  project: default
  sources:
    - path: .
      repoURL: oci://ghcr.io/traefik/helm/traefik-crds
      targetRevision: 1.12.0
      helm:
        releaseName: traefik-crds
    - repoURL: 'https://github.com/theadzik/homelab'
      targetRevision: HEAD
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  sources:
    - path: .
      repoURL: oci://ghcr.io/traefik/helm/traefik
      targetRevision: 37.4.0
      helm:
        releaseName: traefik
        skipCrds: true
        valueFiles:
          - $repo/manifests/base/traefik/values.yaml
    - repoURL: 'https://github.com/theadzik/homelab'
      targetRevision: HEAD
      ref: repo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
