apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs-retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-nfs-retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-nfs-retain-ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metadata
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-nfs-retain-ssd
