# Those services are only created for external-dns to create A-Records
apiVersion: v1
kind: Service
metadata:
  name: nas-1
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "synology.zmuda.pro"
  labels:
    dns-type: internal
spec:
  type: ExternalName
  externalName: 192.168.0.6

---

apiVersion: v1
kind: Service
metadata:
  name: nas-2
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "synology.zmuda.pro"
  labels:
    dns-type: internal
spec:
  type: ExternalName
  externalName: 192.168.0.7
