apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synology-csi
resources:
  - github.com/kubernetes-csi/external-snapshotter/client/config/crd?ref=v8.4.0
  - controller.yml
  - csi-driver.yml
  - external-service.yaml
  - node.yml
  - storage-class.yml
  - snapshotter/snapshotter.yml
  - snapshotter/volume-snapshot-class.yml
secretGenerator:
  - name: client-info-secret
    files:
      - client-info.yml=configs/client-info-secret.yml
