apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-retain
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  formatOptions: '--nodiscard'
reclaimPolicy: Retain
allowVolumeExpansion: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-delete
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  formatOptions: '--nodiscard'
reclaimPolicy: Delete
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-retain
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  mountPermissions: '0755'
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Retain
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-delete
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  mountPermissions: '0755'
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Delete
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-retain-ssd
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  formatOptions: '--nodiscard'
  location: "/volume2"
reclaimPolicy: Retain
allowVolumeExpansion: true

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-delete-ssd
provisioner: csi.san.synology.com
parameters:
  fsType: 'btrfs'
  formatOptions: '--nodiscard'
  location: "/volume2"
reclaimPolicy: Delete
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-retain-ssd
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  mountPermissions: '0755'
  location: "/volume2"
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Retain
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-retain-ssd-postgres
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  mountPermissions: "0750"
  location: "/volume2"
mountOptions:
  - nfsvers=4.1
  - hard
reclaimPolicy: Retain
allowVolumeExpansion: true

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-nfs-delete-ssd
provisioner: csi.san.synology.com
parameters:
  protocol: "nfs"
  mountPermissions: '0755'
  location: "/volume2"
mountOptions:
  - nfsvers=4.1
reclaimPolicy: Delete
allowVolumeExpansion: true
