apiVersion: gateway.networking.x-k8s.io/v1alpha1
kind: XListenerSet
metadata:
  name: media-listeners
spec:
  parentRef:
    name: https
    namespace: kgateway-system
    kind: Gateway
    group: gateway.networking.k8s.io
  listeners:
    - name: media-listeners
      protocol: HTTPS
      port: 443
      hostname: "jellyfin.test.zmuda.pro"
      tls:
        mode: Terminate
        certificateRefs:
          - name: jellyfin-test-zmuda-pro-tls

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
  labels:
    dns-type: internal
spec:
  hostnames:
    - jellyfin.test.zmuda.pro
  parentRefs:
    - name: media-listeners
      kind: XListenerSet
      group: gateway.networking.x-k8s.io
      sectionName: media-listeners
  rules:
    - backendRefs:
        - name: jellyfin
          port: 8096
