apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  project: default
  source:
    path: manifests/base/cloudflared
    repoURL: 'https://github.com/theadzik/homelab'
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: cloudflared
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "cloudflared"
      writeBackConfig:
        method: "git"
      images:
        - alias: "cloudflared"
          imageName: "cloudflare/cloudflared"
          commonUpdateSettings:
            updateStrategy: "semver"
            allowTags: "regexp:^[0-9]{4}\\.[0-9]+\\.[0-9]+$"
