apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources: []
#  - audiobookshelf.yaml
#  - cert-manager.yaml
#  - cloudflared.yaml
#  - cnpg.yaml
#  - crowdsec.yaml
#  - external-dns.yaml
#  - gateway.yaml
#  - gateway-api-crd.yaml
#  - intel-device-plugin.yaml
#  - kgateway.yaml
#  - kube-prometheus-stack.yaml
#  - kube-prometheus-stack-crd.yaml
#  - media.yaml
#  - pihole.yaml
#  - priority-classes.yaml
# - reddit-meaningofwords.yaml
#  - synology-csi.yaml
#  - tandoor.yaml
#  - vaultwarden.yaml
#  - vpa.yaml
#  - wishlist.yaml
#  - zmuda-pro-blog.yaml
