apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reddit-meaningofwords
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: reddit=theadzik/meaningofwords,bullying=theadzik/bullying-detector
    argocd-image-updater.argoproj.io/reddit.update-strategy: semver
    argocd-image-updater.argoproj.io/bullying.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    path: manifests/base/reddit-meaningofwords
    repoURL: 'https://github.com/theadzik/homelab'
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: reddit-meaningofwords
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
