apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zmuda-pro-blog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/base/zmuda-pro-blog
    repoURL: 'https://github.com/theadzik/homelab'
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: zmuda-pro-blog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: zmuda-pro-blog
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "zmuda-pro-blog"
      writeBackConfig:
        method: "git"
      images:
        - alias: "zmuda-pro-blog"
          imageName: "theadzik/zmuda-pro-blog"
          commonUpdateSettings:
            updateStrategy: "semver"
            allowTags: "regexp:^[0-9]{4}\\.[0-9]+\\.[0-9]+$"
