apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec
generatorOptions:
  disableNameSuffixHash: true
resources:
  - enroll-key-secret.yaml
  - traefik-apikey-secret.yaml
