apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: blog
resources:
  - deployment.yaml
  - ingress.yaml
  - middleware-redirect-https.yaml
  - namespace.yaml
  - netpol.yaml
  - service.yaml
  - vpa.yaml
  - ../image-pull-secret
