apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: downloads
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 7Ti
  storageClassName: synology-nfs-retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-ssd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: synology-iscsi-retain-ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config-ssd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: synology-iscsi-retain-ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-ssd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: synology-iscsi-retain-ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config-ssd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-iscsi-retain-ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-intermediate
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Gi
  storageClassName: synology-iscsi-delete-ssd

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-ssd
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: synology-iscsi-retain-ssd
