apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-prod
  labels:
    dns-type: internal
  name: recipes
spec:
  ingressClassName: nginx
  rules:
    - host: tandoor.zmuda.pro
      http:
        paths:
          - backend:
              service:
                name: recipes
                port:
                  number: 8080
            path: /
            pathType: Prefix
          - backend:
              service:
                name: recipes
                port:
                  number: 80
            path: /media
            pathType: Prefix
          - backend:
              service:
                name: recipes
                port:
                  number: 80
            path: /static
            pathType: Prefix
  tls:
    - hosts:
        - tandoor.zmuda.pro
      secretName: tandoor-zmuda-pro-tls
