apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tandoor
resources:
  - configmap.yaml
  - deployment.yaml
  - ingress.yaml
  - nwp.yaml
  - secret.yaml
  - service.yaml
  - serviceaccount.yaml
