apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-nfs-retain

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: synology-nfs-retain
