apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-backup
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,Prune=false
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "synology-nfs-retain"
