apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
spec:
  serviceName: "vaultwarden-http"
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
      ingress: exposed
  template:
    metadata:
      labels:
        app: vaultwarden
        ingress: exposed
    spec:
      priorityClassName: high-priority
      imagePullSecrets:
        - name: dockerhub-image-pull-secret
      initContainers:
        - name: restore
          image: theadzik/vw-restore:2026.2.1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /home/vaultwarden
              name: rclone-conf
            - mountPath: /data
              name: data
            - mountPath: /backup
              name: backup
            - mountPath: /tmp
              name: tmp
          envFrom:
            - secretRef:
                name: backup-encryption-secret
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.33.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: "TCP"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
          envFrom:
            - secretRef:
                name: vw-secrets
          env:
            - name: DOMAIN
              value: 'https://vault.zmuda.pro'
            - name: SIGNUPS_ALLOWED
              value: 'false'
            - name: SIGNUPS_VERIFY
              value: 'true'
            - name: PUSH_ENABLED
              value: 'true'
          volumeMounts:
            - mountPath: /data
              name: data
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden
        - name: backup
          persistentVolumeClaim:
            claimName: vaultwarden-backup
        - name: rclone-conf
          secret:
            secretName: rclone-secret
        - name: tmp
          emptyDir: {}
