apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: blog-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: zmuda-pro-blog
  updatePolicy:
    updateMode: "InPlaceOrRecreate"
