apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-sync
  labels:
    app.kubernetes.io/name: pihole
    app.kubernetes.io/component: sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
      app.kubernetes.io/component: sync
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pihole
        app.kubernetes.io/component: sync
    spec:
      containers:
        - name: sync
          image: ghcr.io/lovelaze/nebula-sync:v0.11.1
          env:
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-password
                  key: WEBPASSWORD
            - name: PRIMARY
              value: http://pihole-primary-0.pihole-dns|$(WEBPASSWORD)
            - name: REPLICAS
              value: http://pihole-secondary-0.pihole-dns|$(WEBPASSWORD),http://pihole-secondary-1.pihole-dns|$(WEBPASSWORD),http://192.168.0.6:8080|$(WEBPASSWORD)
            - name: FULL_SYNC
              value: "true"
            - name: RUN_GRAVITY
              value: "true"
            - name: CRON
              value: "*/1 * * * *"
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
