apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: pihole-netpol
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: pihole
      app.kubernetes.io/component: dns-server
  ingress:
    - fromEntities:
        - "all"
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: TCP
            - port: "53"
              protocol: UDP
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: traefik
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: external-dns
            app.kubernetes.io/instance: pihole
        - matchLabels:
            app.kubernetes.io/component: sync
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
