apiVersion: v2
appVersion: v0.9.0
dependencies:
- alias: nfd
  condition: nfd.enabled
  name: node-feature-discovery
  repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
  version: 0.16.6
description: A Helm chart for a Dynamic Resource Allocation (DRA) Intel GPU Resource
  Driver
home: https://github.com/intel/helm-charts
name: intel-gpu-resource-driver
type: application
version: 0.9.0
