apiVersion: v1
kind: PersistentVolume
metadata:
  name: wishlist-pv
  annotations:
    argocd.argoproj.io/sync-options: Delete=false
spec:
  storageClassName: "synology-nfs-retain"
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    name: wishlist-pvc
    namespace: wishlist
  nfs:
    path: /volume1/games-wishlist
    server: 192.168.0.6
