TZ=Europe/Warsaw
FTLCONF_dns_listeningMode=ALL
FTLCONF_dns_upstreams=1.1.1.1;8.8.8.8;9.9.9.9
FTLCONF_webserver_interface_theme=default-darker
FTLCONF_ntp_ipv4_active=false
FTLCONF_ntp_ipv6_active=false
PIHOLE_UID=1000
PIHOLE_GID=1000
