apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubelet-serving-cert-approver
resources:
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/refs/heads/release-0.10/deploy/standalone-install.yaml
