apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubelet-serving-cert-approver
resources:
  # Install manifest deploys namespace
  - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/refs/tags/v0.10.2/deploy/standalone-install.yaml
