on:
  workflow_call:
    inputs:
      source-tag:
        required: true
        type: string
      docker-repo:
        required: true
        type: string
      context-path:
        required: true
        type: string
      docker-push:
        required: false
        type: boolean
        default: true
      docker-tag:
        required: false
        type: string
        default: "latest"

jobs:
  backup-build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout the tag
        with:
          ref: ${{ inputs.source-tag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build only
        uses: docker/build-push-action@v6
        if: ${{ ! inputs.docker-push }}
        with:
          platforms: "linux/amd64"
          context: "{{defaultContext}}:${{ inputs.context-path }}"
          push: false
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ inputs.docker-push }}
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        if: ${{ inputs.docker-push }}
        with:
          platforms: "linux/amd64"
          context: "{{defaultContext}}:${{ inputs.context-path }}"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ inputs.docker-repo }}:${{inputs.docker-tag }}
